// <auto-generated />
using System;
using Catalogue.InfastructureLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalogue.InfastructureLayer.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240123060307_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Catalogue.DomainLayer.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdutcId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8691edd4-40e2-4c48-b64d-a13dc02109ad"),
                            Category = "Redmi",
                            ImgUrl = "mobile.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Mobiles",
                            ProdutcId = 145,
                            SubCategory = "Redmi7pro"
                        },
                        new
                        {
                            Id = new Guid("defd41d0-2529-4294-86f6-8ba3879fe1fe"),
                            Category = "Iphone",
                            ImgUrl = "mobile.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Mobiles",
                            ProdutcId = 11,
                            SubCategory = "Iphone14pro"
                        },
                        new
                        {
                            Id = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            Category = "Realme",
                            ImgUrl = "mobile.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Mobiles",
                            ProdutcId = 146,
                            SubCategory = "Realme10pro"
                        },
                        new
                        {
                            Id = new Guid("391a17f9-a053-46e5-b0c8-71138939f197"),
                            Category = "Sony",
                            ImgUrl = "TV.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Tv",
                            ProdutcId = 130,
                            SubCategory = "SonyBravia"
                        },
                        new
                        {
                            Id = new Guid("2d3264b3-1ba4-4f6b-b020-7aa1df3ee3b9"),
                            Category = "Samsung",
                            ImgUrl = "TV.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Tv",
                            ProdutcId = 148,
                            SubCategory = "Samsung9pro"
                        },
                        new
                        {
                            Id = new Guid("117d947f-31e4-4a96-b2c2-1e2df09ef429"),
                            Category = "OnePlus",
                            ImgUrl = "TV.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Tv",
                            ProdutcId = 149,
                            SubCategory = "OnePlus9pro"
                        },
                        new
                        {
                            Id = new Guid("4bdf41b9-db10-4923-bdb2-c68a3d4c91d2"),
                            Category = "OnePlus",
                            ImgUrl = "TV.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Tv",
                            ProdutcId = 145,
                            SubCategory = "OnePlus9pro"
                        },
                        new
                        {
                            Id = new Guid("fc794bfc-4fea-48a3-be89-17c71265a9a8"),
                            Category = "Realme",
                            ImgUrl = "TV.jpj",
                            ProductDescription = "it is user friendly",
                            ProductName = "Tv",
                            ProdutcId = 150,
                            SubCategory = "Realme10pro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
